#!/usr/bin/env/python3
# -*- coding:utf-8 -*-
import threading,multiprocessing,os
def loop():
    while True:
        print(threading.current_thread().name,os.getpid())
for i in range(multiprocessing.cpu_count()):
    t = threading.Thread(target = loop)
    t.start()
    print(threading.current_thread().name,os.getpid())
