#!/usr/bin/env/python3
# -*- coding:utf-8 -*-
import threading
balance = 0
lock = threading.Lock()
def change_it(n):
    global balance
    balance += n
    balance -= n
    print(balance)
def run_thread(n):
    for i in range(100000):
        lock.acquire()
        try:
            change_it(i)
        finally:
            lock.release()
a = threading.Thread(target = run_thread,args = (5,))
b = threading.Thread(target = run_thread,args = (8,))
a.start()
b.start()
a.join()
b.join()
print(balance)

    
