#!/usr/bin/env/python3 
# -*- coding:utf-8 -*-
from multiprocessing import Process
import os
def child(a):
    print('a child process %s %s' % (a,os.getpid()))
if __name__ == '__main__':
    print('parent process %s' % os.getpid())
    p = Process(target = child,args = ('test',))
    print('child process will start')
    p.start()
    p.join()
    print('child proess end')
def play(name):
    for i in name:
        print(i)
    print('play %s (%s)' % (name,os.getpid()))
if __name__ =='__main__':
    a = Process(target = play,args = ('music',))
    b = Process(target = play,args = ('game',))
    a.start()
    b.start()
    a.join()
    b.join()
    print('end')
