#!usr/bin/env/python3
# -*- coding:utf-8 -*-
from multiprocessing import Pool
import os,time,random
def long_time_task(name):
    print('Run task %s (%s)...' % (name,os.getpid()))
    start = time.time()
    time.sleep(random.random()*10)
    end = time.time()
    print('Task %s runs %0.2f second.' % (name,(end - start)))
if __name__ == '__main__':
    print('Parent process %s' % os.getpid())
    p = Pool(4)
    for i in range(5):
        p.apply_async(long_time_task,args = (i,))
    print('wait for all subprocesses done...')
    p.close()
    p.join()
    print('everything done')
def play(name):
    print('%s start in %s' % (name,os.getpid()))
    start = time.time()
    time.sleep(random.random()*10)
    end = time.time()
    print('play %s %0.2f second.' % (name,end - start))
if __name__ == '__main__':
    print('parent process %s' % os.getpid())
    a = Pool(4)
    for i in ['game','video','music','computer','read']:
        a.apply_async(play,args = (i,))
    print('wait....')
    p.close()
    p.join()
    print('end')
