#!/usr/bin/env/python3
# -*- coding:utf-8 -*-
from multiprocessing import Process,Queue
import os,time,random
def write(n):
    k = random.random()
    n.put(k)
    print('input',k)
def read(n):
    k = n.get()
    print('output',k)
q = Queue()
a = Process(target = write,args = (q,))
b = Process(target = read,args = (q,))
a.start()
b.start()
a.join()
b.join()
print('end')








