#!/usr/bin/env/python3
# -*- coding:utf-8 -*-
import threading
localName = threading.local()
def process_thread(name):
    localName.name = name
    hello()
def hello():
    print('hello',localName.name)
a = threading.Thread(target = process_thread,args = ('nanhua',))
b = threading.Thread(target = process_thread,args = ('longk',))
c = threading.Thread(target = process_thread,args = ('kill.w',))
a.start()
b.start()
c.start()
a.join()
b.join()
c.join()
print('end')
    
