#!/usr/bin/env/python3
# -*- coding:utf-8 -*-
import time,threading
def newThread():
    print('thread %s is running...' % threading.current_thread().name)
    n = 0 
    while n<5:
        n = n + 1
        print('thread %s >>> %s' % (threading.current_thread().name,n))
    time.sleep(1)
    print('thread %s ended.' % threading.current_thread().name)
print('thread %s is runnning...' % threading.current_thread().name)
t = threading.Thread(target = newThread,name = 'newThread')
t.start()
t.join()
print('%s ended' % threading.current_thread().name)
